#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define APP_UART1_RING_BUFFER_SIZE 256U
#define APP_UART1_LINE_BUFFER_SIZE 128U
#define APP_UART_TX_TIMEOUT_MS 100U
#define APP_ADC_TIMEOUT_MS 10U
#define APP_SENSOR_PERIOD_MS 1000U
#define APP_MOTOR_MONITOR_PERIOD_MS 100U
#define APP_MOTOR_WAKE_DELAY_MS 5U
#define APP_MOTOR_DIRECTION_DEADTIME_MS 20U
#define APP_ADC_VREF_MV 3300U
#define APP_ADC_MAX_VALUE 4095U
#define APP_MOTOR_OVERCURRENT_THRESHOLD_MA 3000U

#define APP_MOTOR_STARTUP_OVERRIDE_DISABLED 0U
#define APP_MOTOR_STARTUP_OVERRIDE_SLEEP 1U
#define APP_MOTOR_STARTUP_OVERRIDE_WAKE 2U
#define APP_MOTOR_STARTUP_OVERRIDE_FORWARD 3U
#define APP_MOTOR_STARTUP_OVERRIDE_REVERSE 4U
#define APP_MOTOR_STARTUP_OVERRIDE_BRAKE 5U

#define APP_MOTOR_TEST_MODE_DISABLED 0U
#define APP_MOTOR_TEST_MODE_STARTUP_OVERRIDE 1U
#define APP_MOTOR_TEST_MODE_AUTO_SEQUENCE 2U

#ifndef APP_MOTOR_TEST_MODE
#define APP_MOTOR_TEST_MODE APP_MOTOR_TEST_MODE_AUTO_SEQUENCE
#endif

#ifndef APP_MOTOR_STARTUP_OVERRIDE_MODE
#define APP_MOTOR_STARTUP_OVERRIDE_MODE APP_MOTOR_STARTUP_OVERRIDE_FORWARD
#endif

#define APP_MOTOR_AUTO_SEQUENCE_STEP_DURATION_MS 10000U

#endif